# Generated by Django 5.1.7 on 2025-04-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_availableclasses_chaptertutor_chapterappointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chaptertutor',
            name='preferred_classes',
        ),
        migrations.RemoveField(
            model_name='generaltutor',
            name='preferred_classes',
        ),
        migrations.AddField(
            model_name='chaptertutor',
            name='preferred_classes',
            field=models.CharField(default=1, max_length=100),
        ),
        migrations.DeleteModel(
            name='AvailableClasses',
        ),
        migrations.AddField(
            model_name='generaltutor',
            name='preferred_classes',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
